#!/bin/bash 

populateStrings(){
    string_usage="Usage: multigpg MODE ARCHIVE [FILE]
    MODE is one of the following:
    c
    create      : Creates a new GPG-encrypted archive named ARCHIVE. 
    ls
    list        : List the contents of ARCHIVE.
    a
    add         : Adds FILE to ARCHIVE. Specify 'all' as FILE to add the contents of the whole directory. Shreds (and removes) the files after adding them.
    ex
    extract     : Extracts FILE from ARCHIVE. Specify 'all' as FILE to extract everything.
    pw
    password    : Changes the password of ARCHIVE
    --help      : prints this help message."
    string_archive_missing="Archive doesn't exist. Aborting."
    string_enter_password="Please enter the password:"
    string_confirm_password="Please confirm your password:"
    string_new_password="Please enter new password:"
    string_wrong_password="Your password didn't work or something else went wrong."
    string_wrong_password_typo="Passwords didn't match."
    string_archive_exists="Archive already exists."
    string_file_missing="File doesn't exist in this archive. Aborting."
    string_replace_file="File already exists in this archive. Would you like to replace it?"
}

printUsage(){
    echo $string_usage
}

parseParameters(){
    if [[ $1 = "create" || $1 = "c" ]]
    then
        mode="create"
    elif [[ $1 = "add" || $1 = "a" ]]
    then
        mode="add"
    elif [[ $1 = "extract" || $1 = "ex" ]]
    then
        mode="extract"
    elif [[ $1 = "password" || $1 = "pw" ]]
    then
        mode="password"
    elif [[ $1 = "--help" ]]
    then
        mode="printUsage"
    else
        mode="printUsage"
    fi
    archive=$2
    if [ ! -f $archive ] && [  $mode != "create" ]
    then
        echo "$string_archive_missing"
        exit 1
    fi
    file=$3
    decrypted_archive=$(basename $archive .gpg)
    working_dir=/tmp/multigpg/$archive
    if [ $mode != "discard" ] && [ $mode != "writeback" ]
    then
        while [ -d $working_dir ]
        do
            working_dir=$working_dir\_other
        done
    fi
}

getPassword(){
    echo "$string_enter_password"
    #save password globally
    read -s password
}

confirmPassword(){
    echo "$string_confirm_password"
    read -s confirm_password
}

decrypt(){
    mkdir -p $working_dir
    if ! $(gpg --batch --passphrase $password -o "$working_dir/$decrypted_archive" -d $archive 2> /dev/null)
    then
        echo "$string_wrong_password"
        exit 1
    fi
}

writeback(){
    gpg --batch --yes --passphrase $password --cipher-algo AES256 -o $archive -c "$working_dir/$decrypted_archive" 
}

shred(){
    #recursively shred all files
    find $working_dir -type f -execdir shred -un 1 '{}' \;
    #remove remaining folders
    rm -r $working_dir
    rmdir /tmp/multigpg 2> /dev/null
    #prevent failure exit code caused by other archives open
    return 0
}

untar(){
    mkdir $working_dir/archive
    tar -C $working_dir/archive -xf $working_dir/$decrypted_archive
}

pack_tar(){
    tar -cf $working_dir/$decrypted_archive -C $working_dir/archive .
}

#only start execution if script is executed directly
if [[ $(basename $0) = "multigpg" ]]
then
    #make variables globally available
    populateStrings
    parseParameters "$@"
    if [[ $mode = "printUsage" ]]
    then 
        printUsage
    elif [[ $mode = "create" ]]
    then
        if [[ -f $archive\.tar.gpg ]]
        then
            echo "$string_archive_exists"
            exit 1
        fi
        getPassword
        #ask for password a second time to prevent typos
        confirmPassword
        if [[ "$password" = "$confirm_password" ]]
        then
            tar cT /dev/null -f $archive\.tar
            gpg --batch --passphrase $password --cipher-algo AES256 -c $archive\.tar
            rm $archive\.tar
        else
            echo "$string_wrong_password_typo"
            exit 1
        fi
    elif [[ $mode = "add" ]]
    then
        getPassword
        decrypt
        untar
        if [ ! -f $working_dir/archive/$(basename $file) ] && [ ! -d $working_dir/archive/$(basename $file) ]
        then
            cp -r $file $working_dir/archive
        else
            echo "$string_replace_file"
            read confirmation
            if [ confirmation = "Y" ] || [ confirmation = "y" ]
            then
                cp -r $file $working_dir/archive
            fi
        fi
        pack_tar
        writeback
        shred
    elif [[ $mode = "extract" ]]
    then
        getPassword
        decrypt
        untar
        if  [ -f $working_dir/archive/$file ]
        then
            cp $working_dir/archive/$file .
        else
            echo "$string_file_missing"
            shred
            exit 1
        fi
        shred
    elif [[ $mode = "password" ]]
    then
        getPassword
        decrypt
        #ask for new password
        echo "$string_new_password"
        read -s new_password
        confirmPassword
        if [[ "$new_password" = "$confirm_password" ]]
        then
            password="$new_password"
            writeback
        else
            echo "$string_wrong_password_typo"
            shred
            exit 1
        fi
        shred
    fi

fi
